### PR TITLE
Fixes menu collapsing to ellipse

### LINKED ISSUE #185: App is no longer mobile friendly
Not sure what happened since I tested this using the mobile format on my browser when developing, but it looks like with the latest UI refresh the site is no longer mobile friendly. The sidebar still shows but is unusable. It just shows an ellipsis.

### PR DESCRIPTION
**Pull request by douglance**
Closes #185

### CODE REVIEW

**Comment by douglance** [comment]
Screen Shot 2021-12-27 at 2 04 59 PM

**Comment by alex-miller-0** [comment]
@douglance is there any way to actually collapse the menu on mobile? It would be nice to stretch the page across the whole width of a small device

**Comment by douglance** [comment]
@alex-miller-0 Like this?

https://user-images.githubusercontent.com/4741454/147590349-d99ba9cf-8206-48de-91fc-ded0bb21baf2.mp4

**Comment by alex-miller-0** [comment]
@douglance Yes! Looks good. Can you work on formatting for those screens as well? Looks like the redesign messed up some things like this: 
image

**Comment by douglance** [comment]
I pushed that hamburger menu change. 

I also fixed those floating tooltips, the margins on the Landing, and also fixed the giant lattice image on the Landing that was bothering me... 😄

File: src/components/main.js [hunk 1]
```diff
@@ -267,8 +269,10 @@ class Main extends React.Component {
     this.state.session.setPage(page);
   }
 
-  handleMenuChange({key}) {
-    this.setState({ menuItem: key })
+  handleMenuChange ({ key }) {
+    const stateUpdate = { menuItem: key }
+    if (this.isMobile()) stateUpdate.collapsed = true
```
Comment (alex-miller-0) [inline src/components/main.js:274]: What is the purpose of this line? You've already set `collasped: true` on L74

File: src/components/main.js [hunk 2]
```diff
@@ -70,6 +71,7 @@ class Main extends React.Component {
     // Listen for window resize
     window.addEventListener('resize', this.updateWidth);
 
+    if (this.isMobile()) this.setState({collapsed: true})
```
Comment (alex-miller-0) [inline src/components/main.js:74]: You should put a handler in `this.updateWidth` as well. I noticed that if I shrink to mobile size, collapse the menu to the hamburger, and then resize to full desktop, the menu disappears completely. Think you could add something like the following to `this.updateWidth`:

```
if (this.isMobile() && !this.state.collapsed) {
  this.setState({ collapsed: true })
} else if (!this.isMobile() && this.state.collapsed) {
  this.setState({ collapsed: false })
}

**Review by alex-miller-0 — COMMENTED** [review]
Smol comments. Looks mostly good. Nice resizing of the massive image :)

File: src/components/main.js (hunk 1 above)
Comment (douglance) [reply src/components/main.js:274]: When the user taps on a menu item, this line collapses the menu for them. 

L74 collapses the menu for mobile uses when the Main component is mounted, so because it doesn't unmount when the content changes, L74 doesn't fire again.

File: src/components/main.js (hunk 2 above)
Comment (douglance) [reply src/components/main.js:74]: That worked well without modification. 👍

**Review by alex-miller-0 — APPROVED** [review]
🍻
